//
//  Swift2KotlinGeneratorImpl+KotlinBindingsPrinting.swift
//  swift-java
//
//  Created by Ennio Italiano on 2026-03-01.
//

import Foundation
import OrderedCollections

// MARK: Printing

extension Swift2KotlinGeneratorImpl {
  func writeExportedKotlinSources() throws {
    var printer = CodePrinter()
    try writeExportedKotlinSources(&printer)
  }
  
  package func writeExportedKotlinSources(_ printer: inout CodePrinter) throws {
    
    var exportedFileNames: OrderedSet<String> = []
    
    let filename = "\(self.swiftModuleName).kt"
    logger.trace("Printing module class: \(filename)")
    printModule(&printer)
    
    if let outputFile = try printer.writeContents(
      outputDirectory: kotlinOutputDirectory,
      javaPackagePath: kotlinPackagePath,
      filename: filename
    ) {
      exportedFileNames.append(outputFile.path(percentEncoded: false))
      logger.info("[swift-java] Generated: \(self.swiftModuleName).kt (at \(outputFile))")
    }
    
    // Write kotlin sources list file
    if let generatedKotlinSourcesListFileOutput = config.generatedJavaSourcesListFileOutput, !exportedFileNames.isEmpty {
      let outputPath = URL(fileURLWithPath: kotlinOutputDirectory).appending(path: generatedKotlinSourcesListFileOutput)
      try exportedFileNames.joined(separator: "\n").write(
        to: outputPath,
        atomically: true,
        encoding: .utf8
      )
      logger.info("Generated file at \(outputPath)")
    }
  }
  
  private func printModule(_ printer: inout CodePrinter) {
    printHeader(&printer)
    printPackage(&printer)
    printImports(&printer)

    printModuleObject(&printer)
  }

  private func printModuleObject(_ printer: inout CodePrinter) {
    printer.printBraceBlock("object \(swiftModuleName)") { printer in
      printRuntimeInit(&printer)

      for decl in analysis.importedGlobalFuncs {
        self.logger.trace("Print global function: \(decl)")
        printNativeDeclaration(&printer, decl)
        printWrapperMethod(&printer, decl)
        printer.println()
      }
    }
  }
  
  private func printHeader(_ printer: inout CodePrinter) {
    printer.print(
      """
      // Generated by jextract-swift
      // Swift module: \(swiftModuleName)
      """
    )
  }
  
  private func printPackage(_ printer: inout CodePrinter) {
    if !kotlinPackage.isEmpty {
      printer.print(
      """
      package \(kotlinPackage)
      """
      )
    }
  }
  
  private func printImports(_ printer: inout CodePrinter) {
    printer.print(
      """
      import org.swift.swiftkit.core.*
      """
    )
  }
  
  private func printRuntimeInit(_ printer: inout CodePrinter) {
    printer.print(
      """
      private const val LIB_NAME = "\(swiftModuleName)"

      init {
        System.loadLibrary(SwiftLibraries.LIB_NAME_SWIFT_JAVA)
        System.loadLibrary(LIB_NAME)
      }
      """
    )
  }
  
  private func printNativeDeclaration(
    _ printer: inout CodePrinter,
    _ decl: ImportedFunc
  ) {
    guard translatedDecl(for: decl) != nil else {
      // Failed to translate. Skip.
      return
    }
    
    printNativeBinding(&printer, decl)
  }
  
  private func printNativeBinding(
    _ printer: inout CodePrinter,
    _ decl: ImportedFunc
  ) {
    guard let translatedDecl = translatedDecl(for: decl) else {
      fatalError("Decl was not translated, \(decl)")
    }
    printNativeBinding(&printer, translatedDecl)
  }
  
  private func printNativeBinding(
    _ printer: inout CodePrinter,
    _ translatedDecl: KotlinTranslatedFunctionDecl
  ) {
    let translatedSignature = translatedDecl.translatedFunctionSignature
    let resultType = translatedSignature.resultType.render()
    let (renderedParameters, _) = renderedParametersAndArguments(from: translatedSignature.parameters)
    
    let nativeSignature =
    "@JvmStatic\nprivate external fun \(translatedDecl.nativeFunctionName)(\(renderedParameters)): \(resultType)"

    printer.print(nativeSignature)
  }
  
  private func printWrapperMethod(
    _ printer: inout CodePrinter,
    _ decl: ImportedFunc
  ) {
    guard translatedDecl(for: decl) != nil else {
      // Failed to translate. Skip.
      return
    }
    
    printBindingWrapperMethod(&printer, decl)
  }
  
  private func printBindingWrapperMethod(
    _ printer: inout CodePrinter,
    _ decl: ImportedFunc
  ) {
    guard let translatedDecl = translatedDecl(for: decl) else {
      fatalError("Decl was not translated, \(decl)")
    }
    printBindingWrapperMethod(&printer, translatedDecl)
  }
  
  private func renderedParametersAndArguments(from parameters: [KotlinParameter]) -> (String, String) {
    let renderedParameters = parameters.map({ $0.renderParameter() }).joined(separator: ", ")
    let argumentNames = parameters.map(\.name).joined(separator: ", ")
    return (renderedParameters, argumentNames)
  }

  private func printBindingWrapperMethod(
    _ printer: inout CodePrinter,
    _ translatedDecl: KotlinTranslatedFunctionDecl
  ) {
    let translatedSignature = translatedDecl.translatedFunctionSignature
    let resultType = translatedSignature.resultType.render()
    let (renderedParameters, argumentNames) = renderedParametersAndArguments(from: translatedSignature.parameters)
    
    let signature =
    "@JvmStatic\nfun \(translatedDecl.name)(\(renderedParameters)): \(resultType)"
    
    let nativeCall = "\(translatedDecl.nativeFunctionName)(\(argumentNames))"
    
    let body = if translatedDecl.translatedFunctionSignature.resultType == .unit {
      nativeCall
    } else {
      "return \(nativeCall)"
    }
    
    printer.printBraceBlock(signature) { printer in
      printer.print(body)
    }
  }
}
