//
//  Swift2KotlinGeneratorImpl+KotlinBindingsPrinting.swift
//  swift-java
//
//  Created by Ennio Italiano on 2026-03-01.
//

import Foundation
import OrderedCollections

// MARK: Printing

extension Swift2KotlinGeneratorImpl {
  func writeExportedKotlinSources() throws {
    var printer = CodePrinter()
    try writeExportedKotlinSources(&printer)
  }
  
  package func writeExportedKotlinSources(_ printer: inout CodePrinter) throws {
    
    var exportedFileNames: OrderedSet<String> = []
    
    let filename = "\(self.swiftModuleName).kt"
    logger.trace("Printing module class: \(filename)")
    printModule(&printer)
    
    if let outputFile = try printer.writeContents(
      outputDirectory: kotlinOutputDirectory,
      javaPackagePath: kotlinPackagePath,
      filename: filename
    ) {
      exportedFileNames.append(outputFile.path(percentEncoded: false))
      logger.info("[swift-java] Generated: \(self.swiftModuleName).kt (at \(outputFile))")
    }
    
    // Write kotlin sources list file
    if let generatedKotlinSourcesListFileOutput = config.generatedJavaSourcesListFileOutput, !exportedFileNames.isEmpty {
      let outputPath = URL(fileURLWithPath: kotlinOutputDirectory).appending(path: generatedKotlinSourcesListFileOutput)
      try exportedFileNames.joined(separator: "\n").write(
        to: outputPath,
        atomically: true,
        encoding: .utf8
      )
      logger.info("Generated file at \(outputPath)")
    }
  }
  
  private func printModule(_ printer: inout CodePrinter) {
    printHeader(&printer)
    printPackage(&printer)
    
    for decl in analysis.importedGlobalFuncs {
      self.logger.trace("Print global function: \(decl)")
      printFunctionDowncallMethods(&printer, decl)
      printer.println()
    }
  }
  
  private func printHeader(_ printer: inout CodePrinter) {
    printer.print(
      """
      // Generated by jextract-swift
      // Swift module: \(swiftModuleName)
      """
    )
  }
  
  private func printPackage(_ printer: inout CodePrinter) {
    if !kotlinPackage.isEmpty {
      printer.print(
      """
      package \(kotlinPackage)
      """
      )
    }
  }
  
  private func printFunctionDowncallMethods(
    _ printer: inout CodePrinter,
    _ decl: ImportedFunc
  ) {
    guard translatedDecl(for: decl) != nil else {
      // Failed to translate. Skip.
      return
    }
    
    printKotlinBindingWrapperMethod(&printer, decl)
  }
  
  private func printKotlinBindingWrapperMethod(
    _ printer: inout CodePrinter,
    _ decl: ImportedFunc
  ) {
    guard let translatedDecl = translatedDecl(for: decl) else {
      fatalError("Decl was not translated, \(decl)")
    }
    printKotlinBindingWrapperMethod(&printer, translatedDecl, importedFunc: decl)
  }
  
  private func printKotlinBindingWrapperMethod(
    _ printer: inout CodePrinter,
    _ translatedDecl: KotlinTranslatedFunctionDecl,
    importedFunc: ImportedFunc? = nil
  ) {
    let translatedSignature = translatedDecl.translatedFunctionSignature
    let resultType = translatedSignature.resultType.render()
    let parameters = translatedDecl.translatedFunctionSignature.parameters.map { $0.renderParameter() }
    let parametersStr = parameters.joined(separator: ", ")
    
    let signature =
    "fun \(translatedDecl.name)(\(parametersStr)): \(resultType)"
    
    printer.printBraceBlock(signature) { printer in
      printer.print("TODO(\"Not implemented\")")
    }
  }
}
